package il.co.tradesmanager.core.audit

/**
 * Every phrase a repository may write into an audit summary.
 *
 * Constants rather than literals at the call sites, so the set of things the
 * register can say is a list somebody can read, and so that
 * tools/gen-audit-strings.py can prove each one has a translation and a
 * branch that renders it. A phrase with no translation shows on a Hebrew
 * screen as the key itself — "tw_released", in the middle of an audit trail —
 * which is the same kind of invisible fault this exists to remove.
 *
 * The words live in tools/data/audit-summaries.json, in three languages, and
 * are generated into the string catalogue from there. Adding a phrase means
 * adding it there, running the generator, and adding a constant here and a
 * branch in ui/audit/SummaryText.kt. The CI check fails until all four exist.
 *
 * Generated by tools/gen-audit-strings.py — the phrase table is the source.
 */
object Summaries {

    /**
     * %1$s admitted at the gate as %2$s
     *
     * Arguments, in order: name, role.
     */
    const val ADMITTED_AT_GATE = "admitted_at_gate"

    /**
     * %1$s v%2$s: %3$s
     *
     * Arguments, in order: reference, version, status.
     */
    const val AMENDMENT_STATUS = "amendment_status"

    /**
     * %1$s certified
     *
     * Arguments, in order: reference.
     */
    const val APPLICATION_CERTIFIED = "application_certified"

    /**
     * %1$s paid
     *
     * Arguments, in order: reference.
     */
    const val APPLICATION_PAID = "application_paid"

    /**
     * %1$s rejected
     *
     * Arguments, in order: reference.
     */
    const val APPLICATION_REJECTED = "application_rejected"

    /**
     * %1$s submitted
     *
     * Arguments, in order: reference.
     */
    const val APPLICATION_SUBMITTED = "application_submitted"

    /**
     * %1$s invoiced
     *
     * Arguments, in order: reference.
     */
    const val ASSIGNMENT_INVOICED = "assignment_invoiced"

    /**
     * %1$s: %2$s to %3$s
     *
     * Arguments, in order: reference, from, to.
     */
    const val ASSIGNMENT_STATUS = "assignment_status"

    /**
     * %1$s: %2$s to %3$s — %4$s
     *
     * Arguments, in order: reference, from, to, reason.
     */
    const val ASSIGNMENT_STATUS_REASON = "assignment_status_reason"

    /**
     * %1$s attended
     *
     * Arguments, in order: name.
     */
    const val ATTENDEE_ADDED = "attendee_added"

    /**
     * %1$s taken off the attendance
     *
     * Arguments, in order: name.
     */
    const val ATTENDEE_REMOVED = "attendee_removed"

    /**
     * Backed up, with %1$s photographs and videos
     *
     * Arguments, in order: count.
     */
    const val BACKUP_MADE = "backup_made"

    /**
     * Copied %1$s time blocks
     *
     * Arguments, in order: count.
     */
    const val BLOCKS_COPIED = "blocks_copied"

    /**
     * Checked in
     */
    const val CHECKED_IN = "checked_in"

    /**
     * Checked out after %1$s minutes
     *
     * Arguments, in order: minutes.
     */
    const val CHECKED_OUT = "checked_out"

    /**
     * Checklist signed
     */
    const val CHECKLIST_SIGNED = "checklist_signed"

    /**
     * Started the checklist %1$s
     *
     * Arguments, in order: name.
     */
    const val CHECKLIST_STARTED = "checklist_started"

    /**
     * Placed
     */
    const val CONCRETE_PLACED = "concrete_placed"

    /**
     * Load rejected: %1$s
     *
     * Arguments, in order: reason.
     */
    const val CONCRETE_REJECTED = "concrete_rejected"

    /**
     * Truck %1$s, %2$s m³
     *
     * Arguments, in order: truck, volume.
     */
    const val CONCRETE_TRUCK = "concrete_truck"

    /**
     * %1$s signed
     *
     * Arguments, in order: reference.
     */
    const val CONTRACT_SIGNED = "contract_signed"

    /**
     * Contract value set
     */
    const val CONTRACT_VALUE_SET = "contract_value_set"

    /**
     * Created from the template %1$s
     *
     * Arguments, in order: template.
     */
    const val CREATED_FROM_TEMPLATE = "created_from_template"

    /**
     * Custom trade removed
     */
    const val CUSTOM_TRADE_REMOVED = "custom_trade_removed"

    /**
     * Daily log signed
     */
    const val DAILY_LOG_SIGNED = "daily_log_signed"

    /**
     * Delivered on %1$s
     *
     * Arguments, in order: reference.
     */
    const val DELIVERED_ON = "delivered_on"

    /**
     * Details corrected for %1$s: %2$s
     *
     * Arguments, in order: name, fields.
     */
    const val DETAILS_CORRECTED = "details_corrected"

    /**
     * %1$s serviced
     *
     * Arguments, in order: name.
     */
    const val EQUIPMENT_SERVICED = "equipment_serviced"

    /**
     * %1$s: %2$s
     *
     * Arguments, in order: name, status.
     */
    const val EQUIPMENT_STATUS = "equipment_status"

    /**
     * Backfilled
     */
    const val EXCAVATION_BACKFILLED = "excavation_backfilled"

    /**
     * Ground disturbed
     */
    const val EXCAVATION_DISTURBED = "excavation_disturbed"

    /**
     * address
     */
    const val FIELD_ADDRESS = "field_address"

    /**
     * email
     */
    const val FIELD_EMAIL = "field_email"

    /**
     * ID number
     */
    const val FIELD_ID_NUMBER = "field_id_number"

    /**
     * contractor licence
     */
    const val FIELD_LICENCE = "field_licence"

    /**
     * name
     */
    const val FIELD_NAME = "field_name"

    /**
     * nothing
     */
    const val FIELD_NOTHING = "field_nothing"

    /**
     * phone
     */
    const val FIELD_PHONE = "field_phone"

    /**
     * registration number
     */
    const val FIELD_REGISTRATION = "field_registration"

    /**
     * website
     */
    const val FIELD_WEBSITE = "field_website"

    /**
     * Received %1$s %2$s of %3$s
     *
     * Arguments, in order: quantity, unit, item.
     */
    const val GOODS_RECEIVED = "goods_received"

    /**
     * Heat check: feels like %1$s°C, %2$s
     *
     * Arguments, in order: index, band.
     */
    const val HEAT_CHECKED = "heat_checked"

    /**
     * ID number set
     */
    const val ID_NUMBER_SET = "id_number_set"

    /**
     * Safety induction signed
     */
    const val INDUCTION_SIGNED = "induction_signed"

    /**
     * %1$s failed inspection
     *
     * Arguments, in order: reference.
     */
    const val INSPECTION_FAILED = "inspection_failed"

    /**
     * %1$s passed inspection
     *
     * Arguments, in order: reference.
     */
    const val INSPECTION_PASSED = "inspection_passed"

    /**
     * %1$s paid
     *
     * Arguments, in order: number.
     */
    const val INVOICE_PAID = "invoice_paid"

    /**
     * Item removed from stock
     */
    const val ITEM_REMOVED = "item_removed"

    /**
     * Joined as %1$s
     *
     * Arguments, in order: role.
     */
    const val JOINED_AS = "joined_as"

    /**
     * Left the company
     */
    const val LEFT_COMPANY = "left_company"

    /**
     * %1$s approved
     *
     * Arguments, in order: reference.
     */
    const val LIFT_APPROVED = "lift_approved"

    /**
     * %1$s lifted
     *
     * Arguments, in order: reference.
     */
    const val LIFT_DONE = "lift_done"

    /**
     * %1$s %2$s cleared
     *
     * Arguments, in order: reference, role.
     */
    const val LIFT_ROLE_CLEARED = "lift_role_cleared"

    /**
     * %1$s %2$s: %3$s
     *
     * Arguments, in order: reference, role, name.
     */
    const val LIFT_ROLE_SET = "lift_role_set"

    /**
     * Marked as a site plan
     */
    const val MARKED_SITE_PLAN = "marked_site_plan"

    /**
     * %1$s added as %2$s
     *
     * Arguments, in order: name, role.
     */
    const val MEMBER_ADDED = "member_added"

    /**
     * Roll call ended, everybody accounted for
     */
    const val MUSTER_ENDED_ALL_OUT = "muster_ended_all_out"

    /**
     * Roll call ended, %1$s unaccounted for: %2$s
     *
     * Arguments, in order: count, names.
     */
    const val MUSTER_ENDED_MISSING = "muster_ended_missing"

    /**
     * %1$s added to the roll call
     *
     * Arguments, in order: name.
     */
    const val MUSTER_PERSON_ADDED = "muster_person_added"

    /**
     * Roll call started (%1$s), %2$s on site
     *
     * Arguments, in order: reason, people.
     */
    const val MUSTER_STARTED = "muster_started"

    /**
     * %1$s cancelled
     *
     * Arguments, in order: reference.
     */
    const val ORDER_CANCELLED = "order_cancelled"

    /**
     * %1$s due %2$s
     *
     * Arguments, in order: reference, date.
     */
    const val ORDER_DUE = "order_due"

    /**
     * %1$s has no delivery date
     *
     * Arguments, in order: reference.
     */
    const val ORDER_NO_DATE = "order_no_date"

    /**
     * %1$s placed
     *
     * Arguments, in order: reference.
     */
    const val ORDER_PLACED = "order_placed"

    /**
     * %1$s: %2$s
     *
     * Arguments, in order: reference, status.
     */
    const val ORDER_STATUS = "order_status"

    /**
     * %1$s added as %2$s
     *
     * Arguments, in order: organisation, party.
     */
    const val PARTY_ADDED = "party_added"

    /**
     * First-tier subcontractor
     */
    const val PARTY_FIRST_TIER = "party_first_tier"

    /**
     * General contractor
     */
    const val PARTY_GENERAL_CONTRACTOR = "party_general_contractor"

    /**
     * Crew leader / labour-only
     */
    const val PARTY_SECOND_TIER = "party_second_tier"

    /**
     * Passcode changed
     */
    const val PASSCODE_CHANGED = "passcode_changed"

    /**
     * Passcode removed
     */
    const val PASSCODE_REMOVED = "passcode_removed"

    /**
     * %1$s cancelled
     *
     * Arguments, in order: reference.
     */
    const val PERMIT_CANCELLED = "permit_cancelled"

    /**
     * %1$s issued to %2$s
     *
     * Arguments, in order: reference, name.
     */
    const val PERMIT_ISSUED = "permit_issued"

    /**
     * %1$s signed back
     *
     * Arguments, in order: reference.
     */
    const val PERMIT_SIGNED_BACK = "permit_signed_back"

    /**
     * %1$s work stopped
     *
     * Arguments, in order: reference.
     */
    const val PERMIT_STOPPED = "permit_stopped"

    /**
     * Photograph removed
     */
    const val PHOTO_REMOVED = "photo_removed"

    /**
     * %1$s checked before use: fit
     *
     * Arguments, in order: name.
     */
    const val PLANT_CHECKED_FIT = "plant_checked_fit"

    /**
     * %1$s checked before use: out of service — %2$s
     *
     * Arguments, in order: name, defect.
     */
    const val PLANT_CHECKED_UNFIT = "plant_checked_unfit"

    /**
     * %1$s sent to site
     *
     * Arguments, in order: name.
     */
    const val PLANT_TO_SITE = "plant_to_site"

    /**
     * %1$s back in the yard
     *
     * Arguments, in order: name.
     */
    const val PLANT_TO_YARD = "plant_to_yard"

    /**
     * %1$s finished
     *
     * Arguments, in order: reference.
     */
    const val POUR_FINISHED = "pour_finished"

    /**
     * Company profile updated; shown to the crew: %1$s
     *
     * Arguments, in order: fields.
     */
    const val PROFILE_PUBLISHED = "profile_published"

    /**
     * Now reports to %1$s
     *
     * Arguments, in order: boss.
     */
    const val REPORTS_TO = "reports_to"

    /**
     * Reports to nobody
     */
    const val REPORTS_TO_NOBODY = "reports_to_nobody"

    /**
     * Restocked
     */
    const val RESTOCKED = "restocked"

    /**
     * Role set to %1$s
     *
     * Arguments, in order: role.
     */
    const val ROLE_SET = "role_set"

    /**
     * Altered
     */
    const val SCAFFOLD_ALTERED = "scaffold_altered"

    /**
     * Dismantled
     */
    const val SCAFFOLD_DISMANTLED = "scaffold_dismantled"

    /**
     * %1$s buried services located
     *
     * Arguments, in order: reference.
     */
    const val SERVICES_LOCATED = "services_located"

    /**
     * %1$s reported fixed
     *
     * Arguments, in order: reference.
     */
    const val SNAG_CLAIMED_FIXED = "snag_claimed_fixed"

    /**
     * %1$s: %2$s
     *
     * Arguments, in order: reference, status.
     */
    const val SNAG_STATUS = "snag_status"

    /**
     * Reported fixed
     */
    const val STATUS_FIXED = "status_fixed"

    /**
     * In progress
     */
    const val STATUS_IN_PROGRESS = "status_in_progress"

    /**
     * Proposed
     */
    const val STATUS_PROPOSED = "status_proposed"

    /**
     * Withdrawn
     */
    const val STATUS_WITHDRAWN = "status_withdrawn"

    /**
     * %1$s to %2$s — %3$s
     *
     * Arguments, in order: from, to, reason.
     */
    const val STOCK_MOVED = "stock_moved"

    /**
     * Done
     */
    const val TASK_DONE = "task_done"

    /**
     * Reopened
     */
    const val TASK_REOPENED = "task_reopened"

    /**
     * %1$s taken off its stage
     *
     * Arguments, in order: task.
     */
    const val TASK_STAGE_CLEARED = "task_stage_cleared"

    /**
     * %1$s moved to %2$s
     *
     * Arguments, in order: task, stage.
     */
    const val TASK_STAGE_SET = "task_stage_set"

    /**
     * Time block removed
     */
    const val TIME_BLOCK_REMOVED = "time_block_removed"

    /**
     * Trade cleared
     */
    const val TRADE_CLEARED = "trade_cleared"

    /**
     * Trade set to %1$s
     *
     * Arguments, in order: trade.
     */
    const val TRADE_SET = "trade_set"

    /**
     * %1$s checked by %2$s
     *
     * Arguments, in order: reference, name.
     */
    const val TW_CHECKED_BY = "tw_checked_by"

    /**
     * %1$s erected
     *
     * Arguments, in order: reference.
     */
    const val TW_ERECTED = "tw_erected"

    /**
     * %1$s inspected against the design
     *
     * Arguments, in order: reference.
     */
    const val TW_INSPECTED = "tw_inspected"

    /**
     * %1$s loaded
     *
     * Arguments, in order: reference.
     */
    const val TW_LOADED = "tw_loaded"

    /**
     * %1$s released for striking
     *
     * Arguments, in order: reference.
     */
    const val TW_RELEASED = "tw_released"

    /**
     * %1$s struck
     *
     * Arguments, in order: reference.
     */
    const val TW_STRUCK = "tw_struck"

    /**
     * Used on site
     */
    const val USED_ON_SITE = "used_on_site"

    /**
     * %1$s: %2$s
     *
     * Arguments, in order: reference, status.
     */
    const val VARIATION_STATUS = "variation_status"

    /**
     * Violation confirmed against %1$s
     *
     * Arguments, in order: name.
     */
    const val VIOLATION_CONFIRMED = "violation_confirmed"

    /**
     * %1$s %2$s of %3$s to %4$s
     *
     * Arguments, in order: quantity, unit, stream, facility.
     */
    const val WASTE_RECORDED = "waste_recorded"

    /**
     * Ticket added for a load to %1$s
     *
     * Arguments, in order: facility.
     */
    const val WASTE_TICKET_ADDED = "waste_ticket_added"
}
