#!/usr/bin/env python3
"""Generate platform resource files from the shared string catalogue.

    shared/i18n/strings.json
        -> android/app/src/main/res/values[-<lang>]/strings.xml
        -> ios/TradesManager/Resources/<lang>.lproj/Localizable.strings
        -> ios/TradesManager/Resources/<lang>.lproj/Localizable.stringsdict
        -> ios/TradesManager/Resources/<lang>.lproj/InfoPlist.strings

Adding a language is a translation job, not a development job: add the
language code to "languages" in strings.json, add that key to every entry,
run this script, and register the code in the two places the guide lists
(docs/LOCALIZATION.md). No application source changes.

Run with --check to verify the generated files are current (used by CI).
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import unicodedata
from xml.sax.saxutils import escape as xml_escape

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOGUE = ROOT / "shared" / "i18n" / "strings.json"
ANDROID_RES = ROOT / "android" / "app" / "src" / "main" / "res"
IOS_RES = ROOT / "ios" / "TradesManager" / "Resources"

# Store-facing permission strings. Both platforms must explain, in the user's
# language, why a permission is wanted: Apple reads these from InfoPlist.strings
# at review time, Android shows them in the app's own rationale screen.
# Microphone and speech recognition were declared here for dictating task
# notes. Neither platform has any speech code, so both stores would have been
# asked to approve a use that could not be demonstrated. They come back with
# the feature. Location stays: iOS genuinely stamps a check-in with a fix
# (see LocationStamp in ScheduleView), even though Android never did.
IOS_INFO_PLIST_KEYS = {
    "NSCameraUsageDescription": "perm_camera_body",
    "NSPhotoLibraryUsageDescription": "perm_camera_body",
    "NSLocationWhenInUseUsageDescription": "perm_location_body",
}

GENERATED_BANNER = "Generated by tools/gen-strings.py from shared/i18n/strings.json. Do not edit by hand."

# The privacy notice, twice: as the screen in the app, and as a page at a URL.
#
# Google Play's listing has a field for a privacy policy URL and will not take
# "it is in the app" for an answer. Writing that page by hand would give the
# store one text and the phone another, and the one nobody looked at would be
# the one that went stale — which for this document is the whole problem.
# Both come off the same keys instead.
PRIVACY = pathlib.Path("docs") / "PRIVACY.md"
PRIVACY_LEAD = "priv_lead"
PRIVACY_SECTIONS = [
    ("priv_where_title", "priv_where_body"),
    ("priv_network_title", "priv_network_body"),
    ("priv_none_title", "priv_none_body"),
    ("priv_perm_title", "priv_perm_body"),
    ("priv_crew_title", "priv_crew_body"),
    ("priv_delete_title", "priv_delete_body"),
    ("priv_future_title", "priv_future_body"),
]


def load() -> dict:
    with CATALOGUE.open(encoding="utf-8") as fh:
        return json.load(fh)


# The plural categories each language actually uses, per CLDR. Android's lint
# requires every one of them; supplying only "one" and "other" is fine for
# English and a build failure for Hebrew or Arabic.
CLDR_QUANTITIES: dict[str, set[str]] = {
    "en": {"one", "other"},
    "he": {"one", "two", "many", "other"},
    "ar": {"zero", "one", "two", "few", "many", "other"},
}


def validate(data: dict) -> list[str]:
    problems: list[str] = []
    languages = data["languages"]
    source = data["sourceLanguage"]
    if source not in languages:
        problems.append(f"sourceLanguage {source!r} is not listed in languages")
    for key, entry in data["strings"].items():
        for lang in languages:
            if not entry.get(lang):
                problems.append(f"strings.{key}: missing {lang}")
    for key, entry in data["plurals"].items():
        for lang in languages:
            forms = entry.get(lang)
            if not forms:
                problems.append(f"plurals.{key}: missing {lang}")
                continue
            if "other" not in forms:
                problems.append(f"plurals.{key}.{lang}: no 'other' form")
            # Android's MissingQuantity lint fails the build over this, and it
            # only shows up three minutes into CI. Catch it here, in a second.
            missing = sorted(CLDR_QUANTITIES.get(lang, {"other"}) - set(forms))
            if missing:
                problems.append(
                    f"plurals.{key}.{lang}: {lang} needs {', '.join(missing)} "
                    f"(CLDR plural categories); Android lint rejects the build without them"
                )
    for key in IOS_INFO_PLIST_KEYS.values():
        if key not in data["strings"]:
            problems.append(f"InfoPlist mapping references unknown key {key!r}")
    # The published page and the in-app screen list the same sections. A key
    # renamed in one and not the other would publish a privacy notice with a
    # hole in it, which is worse than not publishing one.
    for key in [PRIVACY_LEAD] + [k for pair in PRIVACY_SECTIONS for k in pair]:
        if key not in data["strings"]:
            problems.append(f"Privacy page references unknown key {key!r}")
    return problems


def android_escape(text: str) -> str:
    """Android string resource escaping (apostrophes and quotes are literal)."""
    out = xml_escape(text)
    out = out.replace("'", r"\'").replace('"', r"\"")
    if out[:1] in ("@", "?"):
        out = "\\" + out
    return out


def ios_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def android_values_dir(lang: str, source: str) -> pathlib.Path:
    return ANDROID_RES / ("values" if lang == source else f"values-{lang}")


def render_android(data: dict, lang: str) -> str:
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {GENERATED_BANNER} -->", "<resources>"]
    for key, entry in data["strings"].items():
        comment = entry.get("c")
        if comment and lang == data["sourceLanguage"]:
            lines.append(f"    <!-- {xml_escape(comment)} -->")
        lines.append(f'    <string name="{key}">{android_escape(entry[lang])}</string>')
    for key, entry in data["plurals"].items():
        lines.append(f'    <plurals name="{key}">')
        for quantity, text in entry[lang].items():
            lines.append(f'        <item quantity="{quantity}">{android_escape(text)}</item>')
        lines.append("    </plurals>")
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def render_ios_strings(data: dict, lang: str) -> str:
    lines = [f"/* {GENERATED_BANNER} */", ""]
    for key, entry in data["strings"].items():
        comment = entry.get("c")
        if comment:
            lines.append(f"/* {comment} */")
        lines.append(f'"{key}" = "{ios_escape(entry[lang])}";')
    return "\n".join(lines) + "\n"


def render_ios_stringsdict(data: dict, lang: str) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        f"<!-- {GENERATED_BANNER} -->",
        '<plist version="1.0">',
        "<dict>",
    ]
    for key, entry in data["plurals"].items():
        lines += [
            f"    <key>{key}</key>",
            "    <dict>",
            "        <key>NSStringLocalizedFormatKey</key>",
            "        <string>%#@count@</string>",
            "        <key>count</key>",
            "        <dict>",
            "            <key>NSStringFormatSpecTypeKey</key>",
            "            <string>NSStringPluralRuleType</string>",
            "            <key>NSStringFormatValueTypeKey</key>",
            "            <string>d</string>",
        ]
        for quantity, text in entry[lang].items():
            lines.append(f"            <key>{quantity}</key>")
            lines.append(f"            <string>{xml_escape(text)}</string>")
        lines += ["        </dict>", "    </dict>"]
    lines += ["</dict>", "</plist>"]
    return "\n".join(lines) + "\n"


def render_ios_infoplist(data: dict, lang: str) -> str:
    lines = [f"/* {GENERATED_BANNER} */", ""]
    for plist_key, string_key in IOS_INFO_PLIST_KEYS.items():
        lines.append(f'"{plist_key}" = "{ios_escape(data["strings"][string_key][lang])}";')
    return "\n".join(lines) + "\n"


def write(path: pathlib.Path, content: str, check: bool, stale: list[str]) -> None:
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(str(path.relative_to(ROOT)))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def render_privacy(data: dict) -> str:
    """The privacy notice as one page, every language on it.

    One file rather than three, because whoever pastes a URL into a store
    listing pastes one, and a reader who wants the other language should not
    have to be handed a different link to find it.
    """
    lines = [
        f"<!-- {GENERATED_BANNER} -->",
        "",
        "# Privacy",
        "",
        "This is the same notice the app shows at **Settings → About → Privacy",
        "policy**, published here so it has a web address. Both come from the same",
        "source; neither can drift from the other.",
    ]
    for lang in data["languages"]:
        heading = data["strings"]["app_name"][lang]
        lines += ["", "---", "", f"## {heading} — {lang}", "",
                  f"**{data['strings'][PRIVACY_LEAD][lang]}**"]
        for title, body in PRIVACY_SECTIONS:
            lines += ["", f"### {data['strings'][title][lang]}", "",
                      data["strings"][body][lang]]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    data = load()
    problems = validate(data)
    if problems:
        print("Translation catalogue is incomplete:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    stale: list[str] = []
    for lang in data["languages"]:
        write(android_values_dir(lang, data["sourceLanguage"]) / "strings.xml",
              render_android(data, lang), args.check, stale)
        lproj = IOS_RES / f"{lang}.lproj"
        write(lproj / "Localizable.strings", render_ios_strings(data, lang), args.check, stale)
        write(lproj / "Localizable.stringsdict", render_ios_stringsdict(data, lang), args.check, stale)
        write(lproj / "InfoPlist.strings", render_ios_infoplist(data, lang), args.check, stale)

    write(ROOT / PRIVACY, render_privacy(data), args.check, stale)

    if args.check:
        if stale:
            print("These generated files are out of date — run tools/gen-strings.py:", file=sys.stderr)
            for path in stale:
                print(f"  - {path}", file=sys.stderr)
            return 1
        print("Generated string resources are up to date.")
        return 0

    rtl = [lang for lang in data["languages"]
           if unicodedata.bidirectional(data["strings"]["app_name"][lang][0]) in ("R", "AL")]
    print(f"Wrote resources for {len(data['languages'])} languages "
          f"({len(data['strings'])} strings, {len(data['plurals'])} plurals).")
    print(f"Right-to-left languages detected: {', '.join(rtl) or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
